name: Container Image Security Scan

on:
  pull_request:
    branches: ["main"]

jobs:
  container_scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for scanning
        # Se construye la imagen que será escaneada.
        # Usamos -f Dockerfile para asegurar que se usa el archivo correcto.
        run: docker build -f Dockerfile -t flask-app-scan:latest .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy vulnerability scanner
        run: |
          # 1. Muestra los resultados en una tabla para una fácil lectura en los logs.
          # Se elimina el flag obsoleto '--vuln-type'. El scanner 'vuln' analiza OS y librerías por defecto.
          trivy image --scanners vuln --format table --ignore-unfixed --severity CRITICAL,HIGH flask-app-scan:latest
          # 2. Genera el reporte en formato SARIF para la integración con GitHub y como artefacto.
          # Aquí sí se usa --exit-code 1 para que el pipeline falle si se encuentran vulnerabilidades.
          trivy image --scanners vuln --format sarif --output trivy-results.sarif --ignore-unfixed --severity CRITICAL,HIGH --exit-code 1 flask-app-scan:latest

      - name: Upload Trivy scan results
        if: always() # Sube el reporte incluso si el paso anterior falla.
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-results.sarif