name: DevSecOps - Security Pipeline on PR

on:
  pull_request:
    branches: ["main"]

jobs:
  security_pipeline:
    runs-on: ubuntu-latest
    permissions:
      issues: write    # Permiso para que la acción de ZAP pueda crear issues.
      contents: read   # Permiso para que la acción de checkout pueda leer el código.
      pull-requests: read # Permiso para que Gitleaks y Dependency Review puedan leer el PR.
      security-events: write # Permiso para subir los reportes SARIF a las alertas de seguridad.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history. Required for Gitleaks to scan PRs correctly.

      # --- 1. SAST Scan (Bandit) ---
      - name: Set up Python for SAST
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        id: bandit_scan
        continue-on-error: true # Permite que el workflow continúe para que los reportes se suban.
        run: bandit -r . -x ./venv -o bandit-report.sarif -f sarif

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4 # Sube el reporte para que el otro workflow pueda usarlo.
        with:
          name: bandit-sast-report
          path: bandit-report.sarif

      - name: Upload Bandit SARIF to GitHub Security
        if: always() # Sube el reporte siempre. La acción es inteligente y no subirá nada si no hay resultados.
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif # El archivo debe existir, incluso si está vacío.

      # --- 1.5. SAST Scan (Gitleaks) ---
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        id: gitleaks_scan
        continue-on-error: true # Permite que el workflow continúe para que los reportes se suban.
        env:
          # Proporciona el token de GitHub como variable de entorno para que la acción pueda escanear Pull Requests.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Gitleaks fallará si encuentra algún secreto.
          fail: true
          # Genera un reporte en formato SARIF para la integración con GitHub.
          report_format: sarif
          report_path: gitleaks-report.sarif

      - name: Upload Gitleaks Report
        if: steps.gitleaks_scan.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sast-report
          path: gitleaks-report.sarif # Se mantiene como artefacto para descarga.

      - name: Upload Gitleaks SARIF to GitHub Security
        if: steps.gitleaks_scan.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif
          category: gitleaks

      # --- 1.6. Dockerfile Hardening (Hadolint) ---
      - name: Run Hadolint Dockerfile Linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          # Esta acción fallará si el Dockerfile no sigue las mejores prácticas.
          ignore: DL3013 # Ignora la advertencia sobre no fijar versiones en pip, ya que usamos requirements.txt

      # --- 1.7. Dependency Review (SCA) ---
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        # Esta acción fallará si el PR introduce una dependencia con una vulnerabilidad conocida.

      # --- 2. DAST Scan (ZAP) ---
      - name: Build Docker image
        run: docker build -f Dockerfile -t flask-app-dast .

      - name: Run Docker container in background
        run: docker run -d --name flask-app-container -p 5000:5000 flask-app-dast

      - name: Wait for application to be ready
        run: |
          echo "Waiting for application to start..."
          timeout 30s bash -c 'until curl -s http://localhost:5000/ > /dev/null; do echo "Waiting for app..."; sleep 2; done'
          echo "Application is ready!"

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        id: zap_scan
        continue-on-error: true # Permite que el workflow continúe para subir el reporte.
        with:
          target: 'http://localhost:5000'
          report_formats: 'sarif,md' # Genera SARIF para Code Scanning y Markdown para artefactos

      - name: Upload ZAP DAST Report
        if: always() # Asegura que el reporte se suba incluso si el escaneo falla
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            report_md.md

      - name: Upload ZAP SARIF to GitHub Security
        if: steps.zap_scan.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report_sarif.sarif

      - name: Stop Docker container
        if: always()
        run: docker stop flask-app-container

      # --- 3. Fail Job if Any Scan Failed (for Issue Creation) ---
      - name: Fail Job if SAST or DAST Scans Found Issues
        if: steps.bandit_scan.outcome == 'failure' || steps.gitleaks_scan.outcome == 'failure' || steps.zap_scan.outcome == 'failure'
        run: |
          echo "Uno o más escaneos (Bandit, Gitleaks, ZAP) encontraron problemas. Fallando el job para activar la creación de un issue."
          exit 1

  container_scan:
    name: Trivy Vulnerability Scan
    # Este job se ejecuta en paralelo con 'security_pipeline' para un feedback más rápido.
    # La dependencia 'needs' ha sido eliminada para permitir la ejecución en paralelo.
    runs-on: ubuntu-latest
    permissions:
      contents: read # para checkout
      security-events: write # para subir el reporte SARIF

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for scanning
        # Se construye la imagen que será escaneada.
        run: docker build -f Dockerfile -t flask-app-scan:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'flask-app-scan:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          scanners: 'vuln'
        continue-on-error: true # Permite que el workflow continúe para subir el reporte
        id: trivy_scan

      - name: Upload Trivy Report as Artifact
        if: steps.trivy_scan.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security
        if: steps.trivy_scan.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'container'

      # --- 3. Fail Job if Trivy Scan Failed (for Issue Creation) ---
      - name: Fail Job if Trivy Found Issues
        if: steps.trivy_scan.outcome == 'failure'
        run: |
          echo "Trivy encontró vulnerabilidades en el contenedor. Fallando el job para activar la creación de un issue."
          exit 1

  threat_modeling:
    name: Threat Modeling (Threagile)
    runs-on: ubuntu-latest
    permissions:
      contents: read # para checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Threagile for Automated Threat Modeling
        uses: threagile/threagile-action@v1
        with:
          model-file: 'microservicio_model.yaml'

      - name: Upload Threat Model Report
        uses: actions/upload-artifact@v4
        with:
          name: threagile-threat-model-report
          path: threagile-reports/